name: TestRegression


on:
  #push: {}
#  schedule:
#    - cron: '0 22 * * *' #  - https://crontab.guru/

  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: "prod"
        description: "Set environment, e.g. `ENV=prod or ENV=shot`"
      arguments:
        required: false
        default: "-m regression"
        description: "pytest additional arguments, e.g. `-m regression`"


jobs:
  playwright:
    name: Regression tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.41.0-jammy
    env:
      AUTH_LOGIN: ${{ secrets.AUTH_LOGIN }}
      AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
    strategy:
      matrix:
        browser: [remote_chrome]
    outputs:
      env_name: ${{ steps.pytest.outputs.env_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt
      #- name: Replace qaseio model imports
      #  run: python3 .github/workflows/replaceQaseioModel.py
      #- name: Find and replace imports in qaseio
      #  run: |
      #    # Знайдемо файл testops.py по всій файловій системі
      #    testops_path=$(find / -name "testops.py" 2>/dev/null | head -n 1)
      #    if [ -z "$testops_path" ]; then
      #      echo "File testops.py not found"
      #      exit 1
      #    fi
      #    # Виконаємо Python-скрипт для заміни імпортів
      #    echo "Found testops.py at: $testops_path"
      #    python3 .github/workflows/replaceQaseioModel.py "$testops_path"
      - name: Find the file and replace the import
        run: |
          FILE=$(find . -type f -path "*site-packages/qaseio/commons/testops.py")
          if [ -n "$FILE" ]; then
            sed -i 's/from qaseio.model/from qaseio.models/g' "$FILE"
          else
            echo "File not found"
          fi
          
      - run: |
          if [ "${{github.event_name}}" = "schedule" ]; then
            export args="-m regression"
            export ENV="prod"
          else
            export ENV='${{github.event.inputs.environment}}'
            export args='${{github.event.inputs.arguments}}'
          fi
            echo "::set-output name=env_name::${ENV:-prod}"
            pytest ${args} --bn ${{ matrix.browser }}
